### ISSUE TITLE
"stoq test" Exceptions

### ISSUE THREAD

**Issue by Kolano** [PUNCH-Cyber/stoq#100]
**Describe the bug**
Running stoq test results in a number of "Unexpected exception" errors

**To Reproduce**
1. stoq test
2. See exceptions...

```
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 546, in scan_payload
    connector.save(response)
  File "<string>", line 3, in save
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 995, in _mock_call
    raise effect
RuntimeError: Unexpected exception
```

**Expected behavior**
Tests to run without exceptions.

Sorry if I'm confused and these exceptions are expected output of tests similar to the "WARNING" messages. If so it may be appropriate to output a message prior to tests indicating such to avoid confusion.

Also probably better to have expected exceptions occur.

**Client (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - stoQ Version v2.0.3

**Exception**
```
stoq test
......[2019-03-01 22:52:11,341 ERROR] stoq: Failed to save results using dummy_connector: {
    "results": [
        {
            "payload_id": "6388b0c7-0665-4227-95b7-3587517622f8",
            "size": 19,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {},
                "dispatch_to": []
            },
            "workers": [
                {}
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    []
                ],
                "archivers": []
            },
            "extracted_from": null,
            "extracted_by": null
        }
    ],
    "request_meta": {
        "archive_payloads": true,
        "source": null,
        "extra_data": {}
    },
    "errors": {},
    "time": "2019-03-01T22:52:11.341154",
    "decorators": {},
    "scan_id": "45c90bde-d7a3-4f83-8d84-9b2d37960c4e"
}
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 546, in scan_payload
    connector.save(response)
  File "<string>", line 3, in save
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 995, in _mock_call
    raise effect
RuntimeError: Unexpected exception
[2019-03-01 22:52:11,341 ERROR] stoq: Failed to save results using dummy_connector: {
    "results": [
        {
            "payload_id": "6388b0c7-0665-4227-95b7-3587517622f8",
            "size": 19,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {},
                "dispatch_to": []
            },
            "workers": [
                {}
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    []
                ],
                "archivers": []
            },
            "extracted_from": null,
            "extracted_by": null
        }
    ],
    "request_meta": {
        "archive_payloads": true,
        "source": null,
        "extra_data": {}
    },
    "errors": {},
    "time": "2019-03-01T22:52:11.341154",
    "decorators": {},
    "scan_id": "45c90bde-d7a3-4f83-8d84-9b2d37960c4e"
}
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 546, in scan_payload
    connector.save(response)
  File "<string>", line 3, in save
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 995, in _mock_call
    raise effect
RuntimeError: Unexpected exception
[2019-03-01 22:52:11,341 ERROR] stoq: Failed to save results using dummy_connector: {
    "results": [
        {
            "payload_id": "6388b0c7-0665-4227-95b7-3587517622f8",
            "size": 19,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {},
                "dispatch_to": []
            },
            "workers": [
                {}
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    []
                ],
                "archivers": []
            },
            "extracted_from": null,
            "extracted_by": null
        }
    ],
    "request_meta": {
        "archive_payloads": true,
        "source": null,
        "extra_data": {}
    },
    "errors": {},
    "time": "2019-03-01T22:52:11.341154",
    "decorators": {},
    "scan_id": "45c90bde-d7a3-4f83-8d84-9b2d37960c4e"
}
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 546, in scan_payload
    connector.save(response)
  File "<string>", line 3, in save
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 995, in _mock_call
    raise effect
RuntimeError: Unexpected exception
[2019-03-01 22:52:11,341 ERROR] stoq: Failed to save results using dummy_connector: {
    "results": [
        {
            "payload_id": "6388b0c7-0665-4227-95b7-3587517622f8",
            "size": 19,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {},
                "dispatch_to": []
            },
            "workers": [
                {}
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    []
                ],
                "archivers": []
            },
            "extracted_from": null,
            "extracted_by": null
        }
    ],
    "request_meta": {
        "archive_payloads": true,
        "source": null,
        "extra_data": {}
    },
    "errors": {},
    "time": "2019-03-01T22:52:11.341154",
    "decorators": {},
    "scan_id": "45c90bde-d7a3-4f83-8d84-9b2d37960c4e"
}
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 546, in scan_payload
    connector.save(response)
  File "<string>", line 3, in save
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 995, in _mock_call
    raise effect
RuntimeError: Unexpected exception
[2019-03-01 22:52:11,341 ERROR] stoq: Failed to save results using dummy_connector: {
    "results": [
        {
            "payload_id": "6388b0c7-0665-4227-95b7-3587517622f8",
            "size": 19,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {},
                "dispatch_to": []
            },
            "workers": [
                {}
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    []
                ],
                "archivers": []
            },
            "extracted_from": null,
            "extracted_by": null
        }
    ],
    "request_meta": {
        "archive_payloads": true,
        "source": null,
        "extra_data": {}
    },
    "errors": {},
    "time": "2019-03-01T22:52:11.341154",
    "decorators": {},
    "scan_id": "45c90bde-d7a3-4f83-8d84-9b2d37960c4e"
}
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 546, in scan_payload
    connector.save(response)
  File "<string>", line 3, in save
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 995, in _mock_call
    raise effect
RuntimeError: Unexpected exception
[2019-03-01 22:52:11,341 ERROR] stoq: Failed to save results using dummy_connector: {
    "results": [
        {
            "payload_id": "6388b0c7-0665-4227-95b7-3587517622f8",
            "size": 19,
            "payload_meta": {
                "should_archive": true,
                "extra_data": {},
                "dispatch_to": []
            },
            "workers": [
                {}
            ],
            "archivers": {},
            "plugins_run": {
                "workers": [
                    []
                ],
                "archivers": []
            },
            "extracted_from": null,
            "extracted_by": null
        }
    ],
    "request_meta": {
        "archive_payloads": true,
        "source": null,
        "extra_data": {}
    },
    "errors": {},
    "time": "2019-03-01T22:52:11.341154",
    "decorators": {},
    "scan_id": "45c90bde-d7a3-4f83-8d84-9b2d37960c4e"
}
Traceback (most recent call last):
  File "/home/pass/.stoq/.venv/lib/python3.6/site-packages/stoq/core.py", line 546, in scan_payload
    connector.save(response)
  File "<string>", line 3, in save
  File "/usr/lib/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 995, in _mock_call
    raise effect
RuntimeError: Unexpected exception
......................................................................[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
[2019-03-01 22:52:12,005 WARNING] stoq: Plugin incompatible_min_stoq_version not compatible with this version of stoQ. Unpredictable results may occur!
.........
----------------------------------------------------------------------
Ran 85 tests in 0.825s

OK
```

**Comment by mlaferrera** [comment]
All normal, when running `stoq test`. The important thing to look at is the bottom, which says it ran 85 tests ok.
